workflows:
  android-apk-build:
    name: GluttonIA Mobile APK
    max_build_duration: 30
    instance_type: linux_x2
    scripts:
      - name: Compilar instalador Debug APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
